---
title: " Shiny Interactive"
#format: html
server: shiny
---

## Introduction

In this example, we will try to define a Quarto document to showcase how we can use `shiny.i18n` in an interactive manner. To learn more about Quarto and how it integrates with R/Shiny, check out the [official documentation](https://quarto.org/docs/interactive/shiny/>).

## An Illustration

Here, we translate a famous quote from the one of the most famous people to have ever existed in tech, **Steve Jobs**...

```{r}

library(shiny)
selectInput(
  inputId = "language",
  label = "Select language: ",
  choices = list("English 🇬🇧" = "en",
                 "Polish 🇵🇱" = "pl",
                 "German 🇩🇪" = "de",
                 "French 🇫🇷" = "fr"),
  selected = "en",
  multiple = FALSE,
  selectize = TRUE
)

htmlOutput("quote")
HTML("<em>— Steve Jobs</em>")
br()
```


```{r}
#| context: server
library(shiny.i18n)

i18n <- Translator$new(translation_json_path = "data/translation.json")
output$quote <- renderText({ i18n$set_translation_language(input$language)
paste0("<blockquote style='text-align: justify;'>", i18n$t("quote"), "</blockquote>")
})
```
```